# Generated by Django 4.0.4 on 2022-05-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='published',
        ),
    ]
