# Generated by Django 4.0.4 on 2022-06-08 09:27

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.png', null=True, upload_to=blogs.models.upload_to),
        ),
    ]
